py3k: These need to return a value since in Py3k they're no longer void
Python 2.x shouldn't care about it though the signature is void there.

As exhibited in error:

dulwich/_diff_tree.c:449:2: error: non-void function 'init_diff_tree'
should return a value [-Wreturn-type]