Fixed HTTPGitServer.get_url() to return a URL which can be connected to. Avoids 9 occurences of the exception
    URLError: <urlopen error [Errno 10061] No connection could be made because
    the target machine actively refused it>

--HG--
extra : rebase_source : 99b38b5688f92e06b80ae7c9cb23930e29044fc2