Close all open file handles in the test case
  dulwich.tests.test_object_store.DiskObjectStoreTests:test_add_thin_pack

to avoid

  WindowsError: [Error 32] The process cannot access the file because it is
  being used by another process: '...\\temp\\tmpdqhxlw\\pack\\pack-08ff98a2737425627a64fab11a4a5c53ed26bf9a.idx'

on Windows.

There should be DiskObjectStore.close() to make this practical!