Do not delete the current working directory to avoid:
    WindowsError: [Error 32] The process cannot access the file because it
    is being used by another process: '...'